<caption>组服务列表</caption>
<thead>
  <tr>
  	<th>展开</th>
    <th>服务器名称</th>
    <th>服务名称</th>
    <th>服务类型</th>
    <th>状态</th>
    <th>操作</th>
    <th>参数配置</th>
    <th>详情监控</th>
  </tr>
</thead>
<tbody></tbody>